SUB_DIRS += \
 \
app

OBJS += \
app/app.o \
app/shell.o \
app/circ_buffer.o \
app/soft_timer.o \
app/event_dispatcher.o \
app/mainloop_timer.o \
app/blinky.o \
app/shellif_usb.o

OBJS_AS_ARGS += \
"app/app.o" \
"app/shell.o" \
"app/circ_buffer.o" \
"app/soft_timer.o" \
"app/event_dispatcher.o" \
"app/mainloop_timer.o" \
"app/blinky.o" \
"app/shellif_usb.o"

DIR_INCLUDES += \
-I"../app"

DEPS_AS_ARGS += \
"app/app.d" \
"app/shell.d" \
"app/circ_buffer.d" \
"app/soft_timer.d" \
"app/event_dispatcher.d" \
"app/mainloop_timer.d" \
"app/blinky.d" \
"app/shellif_usb.d"
